class Tester
  foo as string
  sub new()
    m.foo = "bar"
  end sub
end class

sub Main()
  tester = new Tester()
  ? tester
end sub




' sub Main()
'   game = new BGE.Game(880, 420, true) ' This initializes the game engine
'   game.loadBitmap("ball", "pkg:/sprites/ball.png")
'   ?tester
'   mainRoom = new MainRoom(game)
'   game.defineRoom(mainRoom)
'   game.changeRoom(mainRoom.name)
'   game.centerCanvasToScreen()
'   game.play()
' end sub